# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1373, 889)
        MainWindow.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(550, 100, 496, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.log = QtWidgets.QLabel(MainWindow)
        self.log.setGeometry(QtCore.QRect(180, 40, 151, 151))
        self.log.setText("")
        self.log.setPixmap(QtGui.QPixmap("F:/图片/保存的图片/科大校徽1.jpg"))
        self.log.setScaledContents(True)
        self.log.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.log.setObjectName("log")
        self.layoutWidget = QtWidgets.QWidget(MainWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 210, 731, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.linechart = QCustomPlot(self.layoutWidget)
        self.linechart.setObjectName("linechart")
        self.verticalLayout.addWidget(self.linechart)
        self.fallchart = QCustomPlot(self.layoutWidget)
        self.fallchart.setObjectName("fallchart")
        self.verticalLayout.addWidget(self.fallchart)
        self.layoutWidget1 = QtWidgets.QWidget(MainWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 380, 201, 251))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.testButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.testButton.setObjectName("testButton")
        self.verticalLayout_2.addWidget(self.testButton)
        self.gifButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.gifButton.setObjectName("gifButton")
        self.verticalLayout_2.addWidget(self.gifButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buildUDPButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.buildUDPButton.setObjectName("buildUDPButton")
        self.verticalLayout_3.addWidget(self.buildUDPButton)
        self.breakUDPButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.breakUDPButton.setObjectName("breakUDPButton")
        self.verticalLayout_3.addWidget(self.breakUDPButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.label.setText(_translate("MainWindow", "Deep Learning Signal Classifier"))
        self.testButton.setText(_translate("MainWindow", "单次调试"))
        self.gifButton.setText(_translate("MainWindow", "开始采集"))
        self.buildUDPButton.setText(_translate("MainWindow", "建立UDP"))
        self.breakUDPButton.setText(_translate("MainWindow", "断开UDP"))
from QCustomPlot2 import QCustomPlot
